### ISSUE TITLE
get_addr_utxo throws an error for a tx with the same address for the claim and the change

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbryum#122]
The claim update to `rhino` in `4de9d5f55632424de9bd7eb2b91f84456a48fe373a9e6b8f8e162ff990fb7c3e:0` has the claim address `bDud4pU2ZxZ9F1kTFp7oyDzALoDfUABz3N`. The change for the transaction, `4de9d5f55632424de9bd7eb2b91f84456a48fe373a9e6b8f8e162ff990fb7c3e:1` uses the same address as the claim.

When `Wallet.get_spendable_coins()` is called (such as when making a claim) it throws the error:

    Traceback (most recent call last):
      File "lbryum/wallet.py", line 719, in get_spendable_coins
        c = self.get_addr_utxo(addr)
      File "lbryum/wallet.py", line 630, in get_addr_utxo
        coins.pop(txi)
    KeyError: u'4de9d5f55632424de9bd7eb2b91f84456a48fe373a9e6b8f8e162ff990fb7c3e:0'

The claim/change address in question is `bDud4pU2ZxZ9F1kTFp7oyDzALoDfUABz3N`, which is marked as a change address in the wallet.

**Comment by kaykurokawa** [comment]
I'm skeptical that this claim address and change address being the same is the cause of the issue, I don't see any place in the code where it would cause Wallet.get_addr_io() to return something that would cause this exception in Wallet.get_addr_utxo(). 

Are you able to recreate the issue on your own wallet or lbry-in-a-box testing? 

Would this wallet with this issue be affected by this patch https://github.com/lbryio/lbryum-server/pull/35 ? Because if lbryum-server doesn't send the full utxo to the lbryum client, I could see this exception being raised.
