### ISSUE TITLE
Channel content claim uris specifying the channel claim id fail to resolve

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbryum#143]
`lbry://@dankashuck:1/wizkhalifa-sohigh-cover` and `lbry://@dankashuck/wizkhalifa-sohigh-cover` resolve properly. However, `lbry://@dankashuck#3ee582ea28c5a8d35f83c7125d0d2a48e34ab8ca/wizkhalifa-sohigh-cover` incorrectly returns the `claim` result in the `certificate` return field. This causes [this exception](https://github.com/lbryio/lbry/blob/5ce360511bfb18c716b91c39a975e66444e2ed2b/lbrynet/daemon/Daemon.py#L1480) to be raised by lbrynet-daemon.

**Comment by tzarebczan** [comment]
This will happen anytime a user shares a link from their channel via the app - the app shows the wrong claimid (from the claim, instead of the channel certificate) in the app. Resolve works as Jack mentioned, but download/stream will fail.

**Comment by tzarebczan** [comment]
@jackrobison let me know if I should open an accompanying issue under lbry-app or if this suffices. Not sure if the call back is just incorrect, or the app is getting the wrong information.

**Comment by kaykurokawa** [comment]
This is because 3ee582ea28c5a8d35f83c7125d0d2a48e34ab8ca is not the claim_Id for @dankashuck , its the claim_id for wizkhalifa-sohigh-cover

9d2887f9f11670047f9d7f587705d59e3d58ea92 is the claim_id for @dankashuck and @dankashuck#9d2887f9f11670047f9d7f587705d59e3d58ea92/wizkhalifa-sohigh-cover resolves properly

There needs to be error checking here to check if channel name is as expected : https://github.com/lbryio/lbryum-server/blob/master/lbryumserver/blockchain_processor.py#L1079

**Comment by tzarebczan** [comment]
@kaykurokawa the app side issue which was providing the incorrect claim ID was fixed. Does anything still need to be done on the lbryum side? Your last message mentions some error checking.

**Comment by lyoshenka** [comment]
@tzarebczan does this still happen? reopen if it does

**Comment by tzarebczan** [comment]
@lyoshenka this was fixed a while ago, but per my previous comment, @kaykurokawa mentioned there may need to be some error checking - I'll follow up with him to see if its still warranted.
