### ISSUE TITLE
Add ability to lock wallet for security/seeding purposes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#197]
Currently, the wallet encryption process works as follows: Once the wallet is encrypted, it must be unlocked when the LBRY app is started.  Once it is unlocked, the wallet is a usable state where transactions can be created (publishing, sending, tipping, etc).  

As a user, I may want to run the lbry in the background or simply as a daemon process, but I wouldn't want the wallet to be in a transact-able state for security purposes. This will be common among users who will be seeding content on the network. An option to lock the wallet from creating transactions would be beneficial.

Another use case would be to auto-lock the wallet after a certain amount of inactivity (again, for security purposes).

**Comment by kaykurokawa** [comment]
This is actually a lbry daemon issue. Lbryum can already lock and unlock itself at any time.  

The daemon always assumes that it has access to the wallet when it needs ot use it (when sending transactions, making claims, handling automatic payment for downloading) , which is why it halts startup when wallet is locked.  Thus, whenever the daemon uses the wallet it needs to handle the case when it is locked.

**Comment by eukreign** [comment]
@tzarebczan Can this be closed since it's not a lbryum issue per @kaykurokawa last comment?

**Comment by tzarebczan** [comment]
@eukreign - I'll move this over to the daemon repo instead and adjust the the title/description.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry #1113](https://github.com/lbryio/lbry/issues/1113) via [**ZenHub**](https://www.zenhub.com/)
