### ISSUE TITLE
Make a plan for merging lbryum into lbry

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbryum#226]
- [ ] resolve or transfer any remaining valid issues to lbry repository
- [ ] we should remove getclaimtrie from lbryum client and server
- [ ] additionally, the restore command could use some tests (8ed6088)

**Comment by kauffj** [comment]
Some additional requirements IMO:
- [ ] It is possible to run just a wallet in a lightweight way, without being involved in the data network. Ideally, it would be possible to build binaries that exclude the data network functionality entirely, and return a correspondingly smaller subset of API commands.
- [ ] The design pattern accommodates alternative wallet implementations, such as a wallet connected to a full blockchain node rather than an SPV wallet
- [ ] Any API functions that are now surfaced in `lbry` are renamed to follow the `noun_verb` API naming scheme that's been established there

**Comment by jackrobison** [comment]
I think a good starting point would be to remove the `network` (and threading, which almost all there for network operations) from lbryum and replace it with a twisted stratum protocol implementation.

The remaining "real" lbryum (the wallet and functions/classes to make and verify transactions) would remain in place for the time being, as well as `lbrynet.core.Wallet` (which would remain an interface to lbryum `commands`. In lbrynet we'd update `lbrynet.core.Wallet` to `connectTCP` instead of `network.start()`.

**Comment by eukreign** [comment]
I've incorporated almost all of the feedback into a final plan, #230. I left out the "alternative wallet implementations" request since that can be done after the merge, it seems like a new feature.
